package com.otaviobarreto.pokedex.ui

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CatchingPokemon
import androidx.compose.material.icons.filled.ChevronLeft
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.GridView
import androidx.compose.material.icons.filled.Inventory2
import androidx.compose.material.icons.filled.Landscape
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.graphics.ColorMatrix
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import com.otaviobarreto.pokedex.data.CollectionStore
import com.otaviobarreto.pokedex.data.GameContext
import com.otaviobarreto.pokedex.data.GameDexService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

private val BoxBg=Color(0xFFFBF8FF);private val BoxSurface=Color(0xFFF1EEFA);private val BoxSurfaceStrong=Color(0xFFE9E4F5);private val BoxAccent=Color(0xFF7563C9);private val BoxMint=Color(0xFF67D7CB);private val BoxInk=Color(0xFF171522);private val BoxMuted=Color(0xFF777286)
private data class BoxV2Region(val label:String,val source:String,val badge:String)
private data class BoxV2GameGroup(val label:String,val accent:Color,val accent2:Color,val regions:List<BoxV2Region>)
private val boxV2GameGroups=listOf(
 BoxV2GameGroup("Scarlet / Violet",Color(0xFFB54C5D),Color(0xFF6D55B9),listOf(BoxV2Region("Paldea","Scarlet / Violet · Paldea","Jogo base"),BoxV2Region("Kitakami","Scarlet / Violet · Kitakami","DLC · The Teal Mask"),BoxV2Region("Blueberry","Scarlet / Violet · Blueberry","DLC · The Indigo Disk"))),
 BoxV2GameGroup("Sword / Shield",Color(0xFF35A9C7),Color(0xFFD84E72),listOf(BoxV2Region("Galar","Sword / Shield · Galar","Jogo base"))),
 BoxV2GameGroup("Let's Go Pikachu / Eevee",Color(0xFFE0A929),Color(0xFF9A765A),listOf(BoxV2Region("Kanto","Let's Go Pikachu / Eevee · Kanto","Jogo base"))),
 BoxV2GameGroup("Legends Arceus",Color(0xFF527F7C),Color(0xFF9A7953),listOf(BoxV2Region("Hisui","Legends Arceus · Hisui","Jogo base")))
)

@OptIn(ExperimentalMaterial3Api::class) @Composable fun BoxesV2Screen(onPokemonClick:(Int,String?)->Unit){
 var game by remember{mutableStateOf(boxV2GameGroups.first())};var region by remember{mutableStateOf(game.regions.first())};var dex by remember{mutableStateOf<List<GameDexService.GameDexEntry>>(emptyList())};var loading by remember{mutableStateOf(true)};var page by remember{mutableIntStateOf(0)};var gameMenu by remember{mutableStateOf(false)};var regionMenu by remember{mutableStateOf(false)};var allBoxesOpen by remember{mutableStateOf(false)};var searchOpen by remember{mutableStateOf(false)};val captured=CollectionStore.capturedIds
 LaunchedEffect(region.source){loading=true;page=0;val context=GameContext.fromSource(region.source);dex=if(context==null)emptyList()else runCatching{withContext(Dispatchers.IO){GameDexService.loadGameDex(context)}}.getOrElse{emptyList()};loading=false}
 val pageCount=((dex.size+29)/30).coerceAtLeast(1);val safePage=page.coerceIn(0,pageCount-1);val pageEntries=dex.drop(safePage*30).take(30);val caught=dex.count{it.nationalId in captured};val remaining=(dex.size-caught).coerceAtLeast(0);val rawProgress=if(dex.isEmpty())0f else caught.toFloat()/dex.size;val animatedProgress by animateFloatAsState(rawProgress,tween(500),label="dexProgress");val first=pageEntries.firstOrNull()?.gameNumber?:safePage*30+1;val last=pageEntries.lastOrNull()?.gameNumber?:((safePage+1)*30).coerceAtMost(dex.size)
 val gameAccent by animateColorAsState(game.accent,tween(260),label="gameAccent");val gameAccent2 by animateColorAsState(game.accent2,tween(260),label="gameAccent2")
 Column(Modifier.fillMaxSize().background(BoxBg).padding(horizontal=12.dp)){
  Row(Modifier.fillMaxWidth().padding(top=5.dp,bottom=3.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("POKEDEX",fontSize=27.sp,lineHeight=28.sp,fontWeight=FontWeight.Black,color=BoxInk);Text("C A T C H  E M  ·  T O D A S  A S  R E G I Õ E S",fontSize=7.sp,lineHeight=9.sp,color=BoxMuted,maxLines=1)}}
  Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){
   ExposedDropdownMenuBox(gameMenu,{gameMenu=!gameMenu},Modifier.weight(1.16f)){Surface(Modifier.menuAnchor().fillMaxWidth().height(58.dp),shape=RoundedCornerShape(15.dp),color=gameAccent.copy(alpha=.11f),border=androidx.compose.foundation.BorderStroke(1.5.dp,gameAccent.copy(alpha=.72f))){Row(Modifier.fillMaxSize().padding(horizontal=13.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(50),color=gameAccent.copy(alpha=.16f),modifier=Modifier.size(34.dp)){Box(contentAlignment=Alignment.Center){Icon(Icons.Default.CatchingPokemon,null,tint=gameAccent,modifier=Modifier.size(23.dp))}};Column(Modifier.weight(1f).padding(start=9.dp)){Text("Jogo",fontSize=9.sp,color=gameAccent,fontWeight=FontWeight.Bold);Text(game.label,fontSize=14.sp,fontWeight=FontWeight.Black,color=BoxInk,maxLines=1,overflow=TextOverflow.Ellipsis)};Text("▾",fontSize=16.sp,color=gameAccent)}};ExposedDropdownMenu(gameMenu,{gameMenu=false}){boxV2GameGroups.forEach{o->DropdownMenuItem(text={Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).clip(RoundedCornerShape(50)).background(o.accent));Spacer(Modifier.width(9.dp));Text(o.label,fontWeight=FontWeight.SemiBold)}},onClick={game=o;region=o.regions.first();gameMenu=false})}}}
   ExposedDropdownMenuBox(regionMenu,{regionMenu=!regionMenu},Modifier.weight(.84f)){OutlinedTextField(region.label,{},Modifier.menuAnchor().fillMaxWidth().height(58.dp),readOnly=true,singleLine=true,label={Text(if(game.regions.size>1)"DLC / região" else "Região",fontSize=10.sp)},textStyle=LocalTextStyle.current.copy(fontSize=14.sp,fontWeight=FontWeight.Bold),trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(regionMenu)},shape=RoundedCornerShape(15.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=gameAccent,focusedLabelColor=gameAccent));ExposedDropdownMenu(regionMenu,{regionMenu=false}){game.regions.forEach{o->DropdownMenuItem(text={Column{Text(o.label,fontWeight=FontWeight.SemiBold);Text(o.badge,fontSize=10.sp,color=BoxMuted)}},onClick={region=o;regionMenu=false})}}}
  }
  Card(Modifier.fillMaxWidth().padding(top=6.dp),shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=BoxSurface)){Row(Modifier.fillMaxWidth().height(70.dp).padding(horizontal=12.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(51.dp),contentAlignment=Alignment.Center){CircularProgressIndicator({animatedProgress},Modifier.fillMaxSize(),strokeWidth=5.dp,color=gameAccent,trackColor=BoxSurfaceStrong);Text("${(animatedProgress*100).toInt()}%",fontSize=11.sp,fontWeight=FontWeight.Black,color=BoxInk)};VerticalDivider(Modifier.padding(start=12.dp).height(40.dp),color=BoxSurfaceStrong);BoxV2Stat(Icons.Default.CatchingPokemon,"${dex.size}","Total",Modifier.weight(1f),gameAccent2);VerticalDivider(Modifier.height(40.dp),color=BoxSurfaceStrong);BoxV2Stat(null,"$caught","Capturados",Modifier.weight(1f),BoxMint);VerticalDivider(Modifier.height(40.dp),color=BoxSurfaceStrong);BoxV2Stat(null,"$remaining","Restantes",Modifier.weight(1f),BoxMuted);Surface(shape=RoundedCornerShape(11.dp),color=Color.White.copy(alpha=.66f),modifier=Modifier.width(61.dp).height(50.dp)){Column(Modifier.fillMaxSize().padding(4.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Icon(Icons.Default.Landscape,null,tint=gameAccent,modifier=Modifier.size(14.dp));Text(region.label,fontSize=8.sp,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text(if(region.badge.startsWith("DLC"))"DLC" else "Base",fontSize=7.sp,color=BoxMuted)}}}}
  Row(Modifier.fillMaxWidth().height(50.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){FilledTonalIconButton({page=safePage-1},enabled=safePage>0,modifier=Modifier.size(37.dp),colors=IconButtonDefaults.filledTonalIconButtonColors(containerColor=BoxSurfaceStrong,contentColor=BoxInk)){Icon(Icons.Default.ChevronLeft,"Anterior")};Surface(shape=RoundedCornerShape(13.dp),color=BoxSurface,modifier=Modifier.height(40.dp)){Row(Modifier.padding(horizontal=13.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Inventory2,null,tint=gameAccent,modifier=Modifier.size(21.dp));Spacer(Modifier.width(7.dp));Column{Text("Box ${safePage+1}",fontSize=13.sp,fontWeight=FontWeight.Black,color=BoxInk);Text("Pokémon ${first.toString().padStart(3,'0')} – ${last.toString().padStart(3,'0')}",fontSize=8.sp,color=BoxMuted)}}};FilledTonalIconButton({page=safePage+1},enabled=safePage<pageCount-1,modifier=Modifier.size(37.dp),colors=IconButtonDefaults.filledTonalIconButtonColors(containerColor=gameAccent.copy(alpha=.13f),contentColor=BoxInk)){Icon(Icons.Default.ChevronRight,"Próxima")}}
  Box(Modifier.weight(1f).fillMaxWidth()){when{loading->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator(color=gameAccent)};dex.isEmpty()->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Não foi possível carregar esta Pokédex regional.")};else->AnimatedContent(safePage,transitionSpec={fadeIn(tween(180)) togetherWith fadeOut(tween(140))},label="boxPage",modifier=Modifier.fillMaxSize()){BoxV2Grid(dex.drop(it*30).take(30),captured){p->onPokemonClick(p.nationalId,region.source)}}}}
  Row(Modifier.fillMaxWidth().height(55.dp).padding(top=4.dp,bottom=3.dp),horizontalArrangement=Arrangement.spacedBy(7.dp),verticalAlignment=Alignment.CenterVertically){FilledTonalButton({allBoxesOpen=true},Modifier.weight(1f).fillMaxHeight(),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.filledTonalButtonColors(containerColor=BoxSurfaceStrong,contentColor=BoxInk),contentPadding=PaddingValues(horizontal=9.dp)){Icon(Icons.Default.GridView,null,Modifier.size(20.dp));Spacer(Modifier.width(7.dp));Column{Text("Todas as Boxes",fontSize=11.sp,fontWeight=FontWeight.Bold);Text("Veja todas as $pageCount boxes",fontSize=8.sp,color=BoxMuted)}};FilledTonalButton({searchOpen=true},Modifier.weight(1f).fillMaxHeight(),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.filledTonalButtonColors(containerColor=BoxSurfaceStrong,contentColor=BoxInk),contentPadding=PaddingValues(horizontal=9.dp)){Icon(Icons.Default.Search,null,Modifier.size(21.dp));Spacer(Modifier.width(7.dp));Column{Text("Pesquisar",fontSize=11.sp,fontWeight=FontWeight.Bold);Text("Encontre um Pokémon",fontSize=8.sp,color=BoxMuted)}};Column(Modifier.width(75.dp)){Text("Box ${safePage+1} de $pageCount",fontSize=9.sp,color=BoxMuted);LinearProgressIndicator({if(pageCount<=1)1f else(safePage+1).toFloat()/pageCount},Modifier.fillMaxWidth().height(4.dp).clip(RoundedCornerShape(9.dp)),color=gameAccent,trackColor=BoxSurfaceStrong)}}
 }
 if(allBoxesOpen)ModalBottomSheet({allBoxesOpen=false},containerColor=BoxBg){Column(Modifier.fillMaxWidth().padding(20.dp,8.dp)){Text("Todas as Boxes",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("${game.label} · ${region.label} · $pageCount Boxes",color=BoxMuted);LazyColumn(Modifier.fillMaxWidth().heightIn(max=520.dp)){items((0 until pageCount).toList()){p->val es=dex.drop(p*30).take(30);val c=es.count{it.nationalId in captured};Card(Modifier.fillMaxWidth().padding(vertical=3.dp).clickable{page=p;allBoxesOpen=false},colors=CardDefaults.cardColors(containerColor=BoxSurface)){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween){Text("Box ${p+1}",fontWeight=FontWeight.SemiBold);Text("$c/${es.size} capturados",color=BoxMuted)}}}}}}
 if(searchOpen)BoxV2Search(dex,captured,{searchOpen=false},{p->val i=dex.indexOfFirst{it.nationalId==p.nationalId};if(i>=0)page=i/30;searchOpen=false},{p->searchOpen=false;onPokemonClick(p.nationalId,region.source)})
}
@Composable private fun BoxV2Grid(entries:List<GameDexService.GameDexEntry>,captured:Set<Int>,onPokemonClick:(GameDexService.GameDexEntry)->Unit){Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(4.dp)){repeat(5){row->Row(Modifier.weight(1f).fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(4.dp)){repeat(6){col->val i=row*6+col;Box(Modifier.weight(1f).fillMaxHeight()){entries.getOrNull(i)?.let{p->BoxV2Slot(p,p.nationalId in captured){onPokemonClick(p)}}?:Surface(Modifier.fillMaxSize(),shape=RoundedCornerShape(11.dp),color=BoxSurface.copy(alpha=.45f)){} }}}}}}
@Composable private fun BoxV2Stat(icon:ImageVector?,value:String,label:String,modifier:Modifier=Modifier,tint:Color){Column(modifier,horizontalAlignment=Alignment.CenterHorizontally){if(icon!=null)Icon(icon,null,tint=tint,modifier=Modifier.size(13.dp))else Box(Modifier.size(7.dp).clip(RoundedCornerShape(50)).background(tint));Text(value,fontWeight=FontWeight.Black,fontSize=12.sp,color=BoxInk);Text(label,fontSize=7.sp,color=BoxMuted,textAlign=TextAlign.Center,maxLines=1)}}
@Composable private fun BoxV2Slot(p:GameDexService.GameDexEntry,c:Boolean,onClick:()->Unit){Surface(Modifier.fillMaxSize().clickable(onClick=onClick),shape=RoundedCornerShape(11.dp),color=if(c)Color(0xFFEAE6FA)else BoxSurface){Column(Modifier.fillMaxSize().padding(2.dp),horizontalAlignment=Alignment.CenterHorizontally){AsyncImage(p.spriteUrl,p.name,Modifier.weight(1f).fillMaxWidth(.94f).alpha(if(c)1f else .24f),colorFilter=if(c)null else ColorFilter.colorMatrix(ColorMatrix().apply{setToSaturation(0f)}));Text(formatPokemonName(p.name),fontSize=8.sp,lineHeight=8.sp,color=if(c)BoxInk else BoxMuted,maxLines=1,overflow=TextOverflow.Ellipsis,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth());Text("#${p.gameNumber.toString().padStart(3,'0')}",fontSize=8.sp,lineHeight=9.sp,color=BoxMuted)}}}
private fun formatPokemonName(name:String)=name.split("-"," ").joinToString(" "){it.replaceFirstChar{c->if(c.isLowerCase())c.titlecase()else c.toString()}}
@Composable private fun BoxV2Search(d:List<GameDexService.GameDexEntry>,c:Set<Int>,dismiss:()->Unit,select:(GameDexService.GameDexEntry)->Unit,open:(GameDexService.GameDexEntry)->Unit){var q by remember{mutableStateOf("")};val x=q.trim().removePrefix("#");val r=remember(d,q){if(x.isBlank())emptyList()else d.filter{it.name.contains(x,true)||it.gameNumber.toString()==x||it.nationalId.toString()==x}.take(12)};AlertDialog(dismiss,{Text("Pesquisar Pokémon")},{Column{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),singleLine=true,leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text("Nome ou número")});LazyColumn(Modifier.heightIn(max=360.dp)){items(r,key={it.nationalId}){p->Row(Modifier.fillMaxWidth().clickable{select(p)}.padding(7.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(p.spriteUrl,p.name,Modifier.size(48.dp));Column(Modifier.weight(1f)){Text(formatPokemonName(p.name),fontWeight=FontWeight.SemiBold);Text("#${p.gameNumber.toString().padStart(3,'0')} · ${if(p.nationalId in c)"Capturado" else "Faltando"}")};TextButton({open(p)}){Text("Ficha")}}}}}}, {},{TextButton(dismiss){Text("Fechar")}})}